const fs = require('fs');
const content = fs.readFileSync('C:\\Users\\bally\\.openclaw\\workspace\\speeder_deploy\\unisase.html', 'utf8');
console.log('File size:', content.length, 'chars');
console.log('Has title:', content.includes('UniSASE网络安全'));
console.log('Has unisase-hero:', content.includes('id="unisase-hero"'));
console.log('Has sase-overview:', content.includes('id="sase-overview"'));
console.log('Has sase-security:', content.includes('id="sase-security"'));
console.log('Has sase-components:', content.includes('id="sase-components"'));
console.log('Has sase-cases:', content.includes('id="sase-cases"'));
console.log('Has nav-active:', content.includes('nav-active'));
console.log('Has img_security_1:', content.includes('img_security_1.png'));
console.log('Has UniAuth:', content.includes('UniAuth'));
console.log('Has UniGate:', content.includes('UniGate'));
console.log('Has UniMobile:', content.includes('UniMobile'));
console.log('Has footer:', content.includes('<footer>'));
console.log('Has init3DEffects:', content.includes('init3DEffects'));
console.log('Has page-ready:', content.includes('page-ready'));
console.log('Has scroll-snap-type:', content.includes('scroll-snap-type'));
console.log('Has cursor-ring:', content.includes('cursor-ring'));
console.log('Has splash:', content.includes('id="splash"'));
console.log('Has overview-layout:', content.includes('overview-layout'));
console.log('Has security-grid:', content.includes('security-grid'));
console.log('Has components-grid:', content.includes('components-grid'));
console.log('Has cases-grid:', content.includes('cases-grid'));
